
import {TileType} from "@/store/types.ts";

export const mapData: TileType[] = [
    // Y = 1
    { id: '1-1', x: 1, y: 1, owner: 'human', hasEvent: false }, // Стартовый тайл игрока
    { id: '1-2', x: 2, y: 1, owner: 'human', hasEvent: false },
    { id: '1-3', x: 3, y: 1, owner: 'human', hasEvent: true },
    { id: '1-4', x: 4, y: 1, owner: 'human', hasEvent: false },
    { id: '1-5', x: 5, y: 1, owner: 'human', hasEvent: false },
    { id: '1-6', x: 6, y: 1, owner: 'human', hasEvent: false },
    { id: '1-7', x: 7, y: 1, owner: 'human', hasEvent: true },
    { id: '1-8', x: 8, y: 1, owner: 'human', hasEvent: false },
    { id: '1-9', x: 9, y: 1, owner: 'human', hasEvent: false },
    { id: '1-10', x: 10, y: 1, owner: 'human', hasEvent: false },
    { id: '1-11', x: 11, y: 1, owner: 'human', hasEvent: false },
    { id: '1-12', x: 12, y: 1, owner: 'human', hasEvent: true },

    // Y = 2
    { id: '2-1', x: 1, y: 2, owner: 'human', hasEvent: false },
    { id: '2-2', x: 2, y: 2, owner: 'human', hasEvent: false },
    { id: '2-3', x: 3, y: 2, owner: 'human', hasEvent: false },
    { id: '2-4', x: 4, y: 2, owner: 'human', hasEvent: true },
    { id: '2-5', x: 5, y: 2, owner: 'human', hasEvent: false },
    { id: '2-6', x: 6, y: 2, owner: 'human', hasEvent: false },
    { id: '2-7', x: 7, y: 2, owner: 'human', hasEvent: false },
    { id: '2-8', x: 8, y: 2, owner: 'human', hasEvent: true },
    { id: '2-9', x: 9, y: 2, owner: 'human', hasEvent: false },
    { id: '2-10', x: 10, y: 2, owner: 'human', hasEvent: false },
    { id: '2-11', x: 11, y: 2, owner: 'human', hasEvent: false },
    { id: '2-12', x: 12, y: 2, owner: 'human', hasEvent: false },

    // Y = 3
    { id: '3-1', x: 1, y: 3, owner: 'human', hasEvent: true },
    { id: '3-2', x: 2, y: 3, owner: 'human', hasEvent: false },
    { id: '3-3', x: 3, y: 3, owner: 'human', hasEvent: false },
    { id: '3-4', x: 4, y: 3, owner: 'human', hasEvent: false },
    { id: '3-5', x: 5, y: 3, owner: 'human', hasEvent: true },
    { id: '3-6', x: 6, y: 3, owner: 'human', hasEvent: false },
    { id: '3-7', x: 7, y: 3, owner: 'player', hasEvent: false },
    { id: '3-8', x: 8, y: 3, owner: 'human', hasEvent: false },
    { id: '3-9', x: 9, y: 3, owner: 'human', hasEvent: true },
    { id: '3-10', x: 10, y: 3, owner: 'human', hasEvent: false },
    { id: '3-11', x: 11, y: 3, owner: 'human', hasEvent: false },
    { id: '3-12', x: 12, y: 3, owner: 'human', hasEvent: false },

    // Y = 4
    { id: '4-1', x: 1, y: 4, owner: 'human', hasEvent: false },
    { id: '4-2', x: 2, y: 4, owner: 'human', hasEvent: true },
    { id: '4-3', x: 3, y: 4, owner: 'human', hasEvent: false },
    { id: '4-4', x: 4, y: 4, owner: 'human', hasEvent: false },
    { id: '4-5', x: 5, y: 4, owner: 'human', hasEvent: false },
    { id: '4-6', x: 6, y: 4, owner: 'human', hasEvent: true },
    { id: '4-7', x: 7, y: 4, owner: 'human', hasEvent: false },
    { id: '4-8', x: 8, y: 4, owner: 'human', hasEvent: false },
    { id: '4-9', x: 9, y: 4, owner: 'human', hasEvent: false },
    { id: '4-10', x: 10, y: 4, owner: 'human', hasEvent: true },
    { id: '4-11', x: 11, y: 4, owner: 'human', hasEvent: false },
    { id: '4-12', x: 12, y: 4, owner: 'human', hasEvent: false },

    // Y = 5
    { id: '5-1', x: 1, y: 5, owner: 'human', hasEvent: false },
    { id: '5-2', x: 2, y: 5, owner: 'human', hasEvent: false },
    { id: '5-3', x: 3, y: 5, owner: 'human', hasEvent: true },
    { id: '5-4', x: 4, y: 5, owner: 'human', hasEvent: false },
    { id: '5-5', x: 5, y: 5, owner: 'human', hasEvent: false },
    { id: '5-6', x: 6, y: 5, owner: 'human', hasEvent: false },
    { id: '5-7', x: 7, y: 5, owner: 'human', hasEvent: true },
    { id: '5-8', x: 8, y: 5, owner: 'human', hasEvent: false },
    { id: '5-9', x: 9, y: 5, owner: 'human', hasEvent: false },
    { id: '5-10', x: 10, y: 5, owner: 'human', hasEvent: false },
    { id: '5-11', x: 11, y: 5, owner: 'human', hasEvent: true },
    { id: '5-12', x: 12, y: 5, owner: 'human', hasEvent: false },

    // Y = 6
    { id: '6-1', x: 1, y: 6, owner: 'human', hasEvent: false },
    { id: '6-2', x: 2, y: 6, owner: 'human', hasEvent: false },
    { id: '6-3', x: 3, y: 6, owner: 'human', hasEvent: false },
    { id: '6-4', x: 4, y: 6, owner: 'human', hasEvent: true },
    { id: '6-5', x: 5, y: 6, owner: 'human', hasEvent: false },
    { id: '6-6', x: 6, y: 6, owner: 'human', hasEvent: false },
    { id: '6-7', x: 7, y: 6, owner: 'human', hasEvent: false },
    { id: '6-8', x: 8, y: 6, owner: 'human', hasEvent: true },
    { id: '6-9', x: 9, y: 6, owner: 'human', hasEvent: false },
    { id: '6-10', x: 10, y: 6, owner: 'human', hasEvent: false },
    { id: '6-11', x: 11, y: 6, owner: 'human', hasEvent: false },
    { id: '6-12', x: 12, y: 6, owner: 'human', hasEvent: true },

    // Y = 7
    { id: '7-1', x: 1, y: 7, owner: 'human', hasEvent: true },
    { id: '7-2', x: 2, y: 7, owner: 'human', hasEvent: false },
    { id: '7-3', x: 3, y: 7, owner: 'human', hasEvent: false },
    { id: '7-4', x: 4, y: 7, owner: 'human', hasEvent: false },
    { id: '7-5', x: 5, y: 7, owner: 'human', hasEvent: true },
    { id: '7-6', x: 6, y: 7, owner: 'human', hasEvent: false },
    { id: '7-7', x: 7, y: 7, owner: 'human', hasEvent: false },
    { id: '7-8', x: 8, y: 7, owner: 'human', hasEvent: true },
    { id: '7-9', x: 9, y: 7, owner: 'human', hasEvent: false },
    { id: '7-10', x: 10, y: 7, owner: 'human', hasEvent: false },
    { id: '7-11', x: 11, y: 7, owner: 'human', hasEvent: false },
    { id: '7-12', x: 12, y: 7, owner: 'human', hasEvent: true },

    // Y = 8
    { id: '8-1', x: 1, y: 8, owner: 'human', hasEvent: false },
    { id: '8-2', x: 2, y: 8, owner: 'human', hasEvent: true },
    { id: '8-3', x: 3, y: 8, owner: 'human', hasEvent: false },
    { id: '8-4', x: 4, y: 8, owner: 'human', hasEvent: false },
    { id: '8-5', x: 5, y: 8, owner: 'human', hasEvent: false },
    { id: '8-6', x: 6, y: 8, owner: 'human', hasEvent: true },
    { id: '8-7', x: 7, y: 8, owner: 'human', hasEvent: false },
    { id: '8-8', x: 8, y: 8, owner: 'human', hasEvent: false },
    { id: '8-9', x: 9, y: 8, owner: 'human', hasEvent: true },
    { id: '8-10', x: 10, y: 8, owner: 'human', hasEvent: false },
    { id: '8-11', x: 11, y: 8, owner: 'human', hasEvent: false },
    { id: '8-12', x: 12, y: 8, owner: 'human', hasEvent: false },

    // Y = 9
    { id: '9-1', x: 1, y: 9, owner: 'human', hasEvent: false },
    { id: '9-2', x: 2, y: 9, owner: 'human', hasEvent: false },
    { id: '9-3', x: 3, y: 9, owner: 'human', hasEvent: true },
    { id: '9-4', x: 4, y: 9, owner: 'human', hasEvent: false },
    { id: '9-5', x: 5, y: 9, owner: 'human', hasEvent: false },
    { id: '9-6', x: 6, y: 9, owner: 'human', hasEvent: false },
    { id: '9-7', x: 7, y: 9, owner: 'human', hasEvent: true },
    { id: '9-8', x: 8, y: 9, owner: 'human', hasEvent: false },
    { id: '9-9', x: 9, y: 9, owner: 'human', hasEvent: false },
    { id: '9-10', x: 10, y: 9, owner: 'human', hasEvent: true },
    { id: '9-11', x: 11, y: 9, owner: 'human', hasEvent: false },
    { id: '9-12', x: 12, y: 9, owner: 'human', hasEvent: false },
];


